default:
	clang++ soln.cpp -o soln
	./soln test.txt

test:
	clang++ soln.cpp -o soln
	./soln test.txt


final:
	clang++ soln.cpp -o soln
	./soln input.txt

test2:
	clang++ soln2.cpp -o soln2
	./soln2 test.txt

final2:
	clang++ soln2.cpp -o soln2
	./soln2 input.txt
